server:
  port: 18083
spring:
  application:
    name: canal
  redis:
    host: 120.24.159.237
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  client:
    instances:
      example:
        host: 120.24.159.237
        port: 11111
        userName: root
        password: 123456




